### ISSUE TITLE
Adapta is yours

### ISSUE THREAD

**Issue by tsujan** [PapirusDevelopmentTeam/adapta-kde#1]
Just a suggestion:
Since Adapta (in adapta-kde) is *your* theme, you could replace "Tsu Jan" with your name in its author section. You could also change its description (comment).

**Comment by varlesh** [comment]
Thx, but i'm only customizer, You original author.

**Comment by tsujan** [comment]
> Thx, but i'm only customizer, You original author.

You might want to customize it more and more in future. This is open-source and you're free to do so.

**Comment by varlesh** [comment]
`author=Alexey Varfolomeev, based on KvAdapta by Tsu Jan`
It's ok?

**Comment by tsujan** [comment]
Yes :)
