### ISSUE TITLE
GTK2 & GTK3 themes on the KDE Store?

### ISSUE THREAD

**Issue by Warmuser** [PapirusDevelopmentTeam/adapta-kde#11]
I can't find the theme with the same selection color used in your kde theme.  I already tried these: https://www.opendesktop.org/s/Antiques/p/1190851/ but there isn't the same color combination.

**Comment by varlesh** [comment]
i'm not developer GTK Themes. Color combination not possible, because Kvantum not support yet, but on Breeze engine this looking not like Adapta style.

**Comment by SmartFinn** [comment]
@Warmuser there's no original Adapta GTK theme, maybe make sense to ask Adapta developers to upload their theme to the site.

**Comment by Warmuser** [comment]
Ok, thank you guys. @tista500 can you create a compatible version of your GTK Adapta Nokto for these theme?

**Comment by omni6** [comment]
here you see [adapta-gtk](https://github.com/adapta-project/adapta-gtk-theme) compared to adapta/kvantum. i think it matches really good, the fontcolor is slightly different... but i can live with it.

![screenshot_20170921_174329](https://user-images.githubusercontent.com/24492439/30705146-f730f060-9ef4-11e7-8e6e-144ed9879e0a.png)
on which disto are you?

**Comment by Warmuser** [comment]
@omni6 Fedora / Arch (I use both).

**Comment by omni6** [comment]
`pacman -S adapta-gtk-theme`?

**Comment by Warmuser** [comment]
Thanks for the help. But I don't understand how to clone and install the packages from the terminal. I have already enabled the Copr repository:

vmaccount@localhost ~]$ sudo dnf copr enable heikoada/gtk-themes
[sudo] password for vmaccount: 

You are about to enable a Copr repository. Please note that this
repository is not part of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you want to continue? [y/N]: y
Repository successfully enabled.

But how to proceed now? If I try to download the package I get these page: https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/repo/fedora-26/heikoada-gtk-themes-fedora-26.repo

**Comment by SmartFinn** [comment]
@Warmuser execute `sudo dnf install adapta-gtk-theme` to install the package.

**Comment by Warmuser** [comment]
@SmartFinn Nope, it doesn't work.. I already tried these command and this is the resoult: 

[vmaccount@localhost ~]$ sudo dnf install adapta-gtk-theme
[sudo] password for vmaccount: 
Last metadata expiration check: 1:48:13 ago on Fri 13 Oct 2017 03:49:07 PM CEST.
  * Maybe you meant: adapta-gtk-theme
No match for argument: adapta-gtk-theme
Error: Unable to find a match
[vmaccount@localhost ~]$

**Comment by Warmuser** [comment]
Ok, I have reinstalled the https://www.opendesktop.org/s/Antiques/p/1190851/ and I set the Adapta Cyan theme. Thanks to everybody! :)
