### ISSUE TITLE
opensuse repo

### ISSUE THREAD

**Issue by KottV** [PapirusDevelopmentTeam/adapta-kde#12]
Hello!

https://software.opensuse.org/download.html?project=home:kill_it&package=adapta-kde
https://build.opensuse.org/package/show/home:kill_it/adapta-kde

**Comment by varlesh** [comment]
Спасибо, ща добавлю

**Comment by SmartFinn** [comment]
@varlesh погоди, я уже  добавляю :)

**Comment by varlesh** [comment]
ok )

**Comment by SmartFinn** [comment]
@KottV добавил. Спасибо :+1:
