### ISSUE TITLE
Icon theme is not installed correctly when one tries to install it via KDE system settings (get new theme)

### ISSUE THREAD

**Issue by lucasrunner** [PapirusDevelopmentTeam/adapta-kde#13]
The problem is that the archive from that link https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170921.tar.gz has unnecessary folder inside. The icon folders should be archived directly (see the link)
[papirus-icon-theme-20170921.tar.gz](https://github.com/PapirusDevelopmentTeam/adapta-kde/files/1322634/papirus-icon-theme-20170921.tar.gz)

**Comment by varlesh** [comment]
How you find this link?

**Comment by varlesh** [comment]
And why https://github.com/PapirusDevelopmentTeam/adapta-kde/files/1322634/papirus-icon-theme-20170921.tar.gz?
`adapta-kde` - it's not papirus icon theme! It's different repos

**Comment by SmartFinn** [comment]
@varlesh there is no magic, he just attach the archive to comment ;)

**Comment by SmartFinn** [comment]
@lucasrunner we can't control the archives, this archives created by GitHub.

**Comment by SmartFinn** [comment]
@varlesh alternatively, we can attach flat archive to each release, and give a link to it on stoke.kde.org. It's easy to make:

```
git archive --format=tar.gz master -o ../papirus-icon-theme.tar.gz
```

Probably I can automate it via GitHub API.

**Comment by varlesh** [comment]
@lucasrunner i'm upload this soon manually

**Comment by varlesh** [comment]
uploaded
