### ISSUE TITLE
Adapta-Nokto: LibreOffice toolbar unreadable 

### ISSUE THREAD

**Issue by andreasjacob** [PapirusDevelopmentTeam/adapta-kde#14]
Hi, first of all I would like to say that I really love the theme. I think its amazing and great work. Goes really well on Plasma.

But, I'm a regular user of LibreOffice and it has become nearly impossible for me to use because the toolbar icons are hidden in the dark background. Please see the screenshot: https://imgur.com/a/rD6wB

Do you have any suggestion what should I do to make it at least usable? I really dont want to switch back from Adapta-Noko! :(

For comparison, this is how LibreOffice looks with Breeze-dark: http://i.imgur.com/dwqF6jT.png

Thanks for your time.

**Comment by varlesh** [comment]
LibreOffice - it's GTK application. Adapta KDE - it's customization for KDE/Qt apps.
Use another icon theme, for example papirus-dark:
https://github.com/PapirusDevelopmentTeam/papirus-libreoffice-theme
Or breeze-dark (preinstalled)

**Comment by varlesh** [comment]
Papirus Dark LO icon theme:
![image](https://user-images.githubusercontent.com/8083855/30804959-77d86280-a200-11e7-804b-128f5a449615.png)

**Comment by varlesh** [comment]
Changed on **Tools-Options-LibreOffice-View**
and set **Icon size and style**

**Comment by andreasjacob** [comment]
Thanks for your reply. Regarding gtk/qt incompatible do you think it would be helpful to install adapta-gtk-theme and then choose adapta theme for gtk applications in kde? Or it would not work?

Sorry for my ignorance. I'm fairly new to linux and kde.
