### ISSUE TITLE
Pixel around the menu bar

### ISSUE THREAD

**Issue by Danerd** [PapirusDevelopmentTeam/adapta-kde#15]
Hi, can someone help me with this problem. I can see my background around the menu bar. 

Looks like there is a empty space around the bar.

Does someone have the same trouble?

Edit: I'm using KDE Neon.

![screenshot_20170925_170847](https://user-images.githubusercontent.com/13387689/30816022-171cc412-a215-11e7-818e-3ff7ac231bcb.png)

**Comment by varlesh** [comment]
Yes, it happened because used shadow effect for menubar + toolbar.

**Comment by varlesh** [comment]
@Danerd I not understand you. You say about menubar or panel?

**Comment by varlesh** [comment]
i'm not confirm this:
![image](https://user-images.githubusercontent.com/8083855/30816876-3e0b3ba4-a228-11e7-8944-a7751d677ffc.png)

**Comment by Danerd** [comment]
@varlesh Sorry for my English - I mean the panel.

**Comment by varlesh** [comment]
Try change panel size... maybe it's help you.
And remove plasma cache (+ logout):
```
rm -rf ~/.cache/ico* ~/.cache/plasm*
```

**Comment by Danerd** [comment]
@varlesh Thank you, it worked! Now it's perfect. :-)
