### ISSUE TITLE
Feature request: slight variation of color according to focus

### ISSUE THREAD

**Issue by kupiqu** [PapirusDevelopmentTeam/adapta-kde#16]
One thing I like from Breeze is that it highlights window on focus. I really like how windows look like when using adapta-kde, but when several windows are open, it is difficult to know which one is on focus. That's why I'm proposing a slight variation of color to signal this.

**Comment by varlesh** [comment]
Use KvAdapta this have yet

**Comment by kupiqu** [comment]
Is it otherwise the same?

**Comment by varlesh** [comment]
@kupiqu On Kvantum available themes KvAdapta & KvAdaptaDark - this themes have highlight stroke on window.
I don't want add this effect on my themes, because original GTK theme not have this effect.

**Comment by kupiqu** [comment]
I tried this out, but I see no difference. I may be doing sth wrong or perhaps need to configure sth else beyond the theme in Kvantum Manager :/

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30860552-886f6278-a2d8-11e7-8ce8-6fb7003caf30.png)

**Comment by kupiqu** [comment]
I see. I was actually referring to a slight variation of the background color (specifically in the non-dark version of Adapta), not to the text color. I guess there is no option for that, right?

**Comment by varlesh** [comment]
>I see. I was actually referring to a slight variation of the background color (specifically in the non-dark version of Adapta), not to the text color. I guess there is no option for that, right?

Available KvAdapta too. I don't understand what you want. 
See and compare on left KDE on right GTK:
![image](https://user-images.githubusercontent.com/8083855/30867366-cbd9f212-a2ec-11e7-8cbf-374cd3c6aedb.png)

**Comment by kupiqu** [comment]
Mmm, I am referring to the color of the background, not to the color of the text. I don't see any diff wrt the color of the background in the screenshots so far.

Please see how the color of the background changes depending on focus in the Breeze them:

![image](https://user-images.githubusercontent.com/3875196/30867817-f43b718c-a2aa-11e7-858a-7cee169c3292.png)

**Comment by kupiqu** [comment]
The effect may not need to be so salient, but this feature request asks about this effect. I guess this is not sth that you would consider, given that it does not exist in the gtk theme, I imagine...
