### ISSUE TITLE
App's tooltip close button highlight

### ISSUE THREAD

**Issue by petr-nehez** [PapirusDevelopmentTeam/adapta-kde#17]
When I put a mouse cursor above the close button, the color & background does not change (OK, the color of the cross changes but it is almost unnoticeable).
Could you do anything with that?

mouse OUT:
![image](https://user-images.githubusercontent.com/1265990/30902767-c0c98d6c-a36c-11e7-981b-48ba975cf9a3.png)

mouse IN:
![image](https://user-images.githubusercontent.com/1265990/30902775-cb20d6b2-a36c-11e7-80bf-7ab902d608b9.png)

**Comment by varlesh** [comment]
Sorry, I can't fix that

**Comment by varlesh** [comment]
See other plasma themes, for example Oxygen - this not change hover color too... I think it's draw plasmashell

**Comment by petr-nehez** [comment]
Hmm, I see, that's a pitty :(
