### ISSUE TITLE
No arrows in calibre's menu buttons when using kvantum

### ISSUE THREAD

**Issue by marhkb** [PapirusDevelopmentTeam/adapta-kde#18]
![screenshot_20170930_214857](https://user-images.githubusercontent.com/3630213/31048950-81cb5bbc-a629-11e7-8790-5744aab67bd9.png)
![screenshot_20170930_215352](https://user-images.githubusercontent.com/3630213/31048969-e3a3d918-a629-11e7-9f65-b27f6a3bb5da.png)

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/6

**Comment by varlesh** [comment]
@marhkb But you can enable arrows on kvconfig:
```
[PanelButtonTool]
indicator.size=8
```
