### ISSUE TITLE
Renaming files in krusader is not readable

### ISSUE THREAD

**Issue by marhkb** [PapirusDevelopmentTeam/adapta-kde#19]
[2017-09-30 22-15-20.zip](https://github.com/PapirusDevelopmentTeam/adapta-kde/files/1346738/2017-09-30.22-15-20.zip)

**Comment by varlesh** [comment]
It's krusader bug or Kvantum. Reproduced on Breeze engine?

**Comment by marhkb** [comment]
With default kvantum theme and with breeze the old name is cleared as I begin to type.
[2017-09-30 23-16-12.zip](https://github.com/PapirusDevelopmentTeam/adapta-kde/files/1346761/2017-09-30.23-16-12.zip)

**Comment by varlesh** [comment]
i'm not confirm this (rename to mp4):
[screencast-2017-10-01_01.18.34.zip](https://github.com/PapirusDevelopmentTeam/adapta-kde/files/1346762/screencast-2017-10-01_01.18.34.zip)
KDE Neon 5.10.5
Krusader 2.6.0
KDE Frameworks 5.38.0,
Qt 5.9.1

**Comment by varlesh** [comment]
@marhkb Try upgrade Krusader

**Comment by varlesh** [comment]
@marhkb Also maybe you use old Kvantum version? i'm test this with git version. If you use Ubuntu-based distro you can test it:
https://launchpad.net/~varlesh-l/+archive/ubuntu/test/+files/kvantum_0.10.4ubuntu16.git0420170929_amd64.deb

**Comment by marhkb** [comment]
your archive cannot be opened
`Archive:  screencast-2017-10-01_01.18.34.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of screencast-2017-10-01_01.18.34.zip or
        screencast-2017-10-01_01.18.34.zip.zip, and cannot find screencast-2017-10-01_01.18.34.zip.ZIP, period.`

I use Arch so krusader up to date. I will try with another user.

**Comment by varlesh** [comment]
> your archive cannot be opened

It's not archive - rename **zip** to **mp4**

**Comment by marhkb** [comment]
Tested with another user. The same result. I have exactly the same versions installed as you.
I also tested on another machine without luck.

KDE Neon 5.10.5
Krusader 2.6.0
KDE Frameworks 5.38.0,
Qt 5.9.1
Kvantum-qt5 0.10.4

Maybe it as Arch Linux issue. It would be cool if another Arch user would report back.
Thanks for your effort.

**Comment by varlesh** [comment]
@marhkb I don't know. Also try look LOG for krusader and install `kvantum-qt5-git` package from AUR

**Comment by varlesh** [comment]
@marhkb Bug reproduce on Kvantum 0.10.4 and fixed on fresh git-version. Install git-version :)
Or wait 0.10.5 release

**Comment by marhkb** [comment]
cool. thanks for pointing out. It works.
