### ISSUE TITLE
is this just for developement?

### ISSUE THREAD

**Issue by omni6** [PapirusDevelopmentTeam/adapta-kde#2]
i wrote a PKGBUILD for arch, now i need to know if this Git will stay here or it is just playin?

**Comment by omni6** [comment]
btw this is good

**Comment by varlesh** [comment]
Status: Work in progres.

**Comment by omni6** [comment]
in [AUR](https://aur.archlinux.org/packages/adapta-kde-git/)
Thank you!

**Comment by SmartFinn** [comment]
@omni6 we strongly recommend using our Makefile for packages:

```sh
package() {
  make -C "${srcdir}/${pkgname}" DESTDIR="${pkgdir}/" install
}
```

**Comment by omni6** [comment]
package() {
  make -C "${srcdir}/${**gitname**}" DESTDIR="${pkgdir}/" install
}

is the way it works but anyway this is for sure better. began with this PKGBUILD before the makefile was added.

changed...

**Comment by SmartFinn** [comment]
@omni6 Thanks :+1:
