### ISSUE TITLE
Tooltips impossible to read

### ISSUE THREAD

**Issue by FuturePilot** [PapirusDevelopmentTeam/adapta-kde#20]
One of the recent updates caused tooltips to become impossible to read. Using the regular Adapta color scheme. It looks like there's a really light blue font on a light gray background. Affects Ksysguard and Kmail/Kontact

![screenshot_20171013_114136](https://user-images.githubusercontent.com/4391536/31554453-9cbe5046-b00b-11e7-88f0-6a33a01d8b5f.png)

```
adapta-kde:
  Installed: 20170929-100+pkg1~ubuntu17.04.1
  Candidate: 20170929-100+pkg1~ubuntu17.04.1
  Version table:
 *** 20170929-100+pkg1~ubuntu17.04.1 500
        500 http://ppa.launchpad.net/papirus/papirus/ubuntu zesty/main amd64 Packages
        500 http://ppa.launchpad.net/papirus/papirus/ubuntu zesty/main i386 Packages
        100 /var/lib/dpkg/status
```

Kubuntu 17.04

**Comment by SmartFinn** [comment]
Do you use Kvantum or Breeze engine?

**Comment by varlesh** [comment]
@FuturePilot See previous commit https://github.com/PapirusDevelopmentTeam/adapta-kde/commit/a5c0564fbc7ecd89a79a2e40aafcb1a77f42d96f:
`tooltip.text.color=#414c52`
We wait release Kvantum 0.5.10, because new version have more fixes for Darker themes

**Comment by FuturePilot** [comment]
I am using Kvantum.

kvantum:
  Installed: 0.10.4ubuntu17.0420170924
  Candidate: 0.10.4ubuntu17.0420170924
  Version table:
 *** 0.10.4ubuntu17.0420170924 500
        500 http://ppa.launchpad.net/papirus/papirus/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by varlesh** [comment]
@FuturePilot Kvantum updated, upgrade your system and check

**Comment by FuturePilot** [comment]
Still appears to be broken. I'm using the light color scheme not the dark one.

![screenshot_20171014_105026](https://user-images.githubusercontent.com/4391536/31576676-8d9ba88a-b0cd-11e7-80f6-3f2805b7baf9.png)

`kvantum:
  Installed: 0.10.5ubuntu17.04
  Candidate: 0.10.5ubuntu17.04
  Version table:
 *** 0.10.5ubuntu17.04 500
        500 http://ppa.launchpad.net/papirus/papirus/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status`

**Comment by varlesh** [comment]
not confirm this:
![image](https://user-images.githubusercontent.com/8083855/31576952-edd10f3a-b116-11e7-8d92-1935cec4309c.png)

**Comment by varlesh** [comment]
try delete plasma cache from `~/.cache`

**Comment by FuturePilot** [comment]
Ok, I reset the settings in Kvantum Manager and something seems to have cleared itself out. Looks good now. Kmail also looks good.

![screenshot_20171015_115610](https://user-images.githubusercontent.com/4391536/31586539-733ecb9c-b1a0-11e7-961b-64928faa8e05.png)
