### ISSUE TITLE
Window border is messed up when set to "No Borders"

### ISSUE THREAD

**Issue by TamasBarta** [PapirusDevelopmentTeam/adapta-kde#21]
Hi,
the theme is super cool, but when I use the "Adapta" window decoration (in combination with the provided Kvantum theme), I experience that the edge of the window contents and title bar are not aligned. See Image attached of Dolphin.

![screenshot_20171019_123235](https://user-images.githubusercontent.com/1753591/31767028-f5450fda-b4c9-11e7-8a57-d6a0298600ce.png)

System details:

* KDE Plasma Version: 5.11.1
* KDE Frameworks Version: 5.39.0
* Qt Version: 5.9.2

Adapta KDE installed from AUR by `adapta-kde` package.

**Comment by varlesh** [comment]
on my pc all fine:
![image](https://user-images.githubusercontent.com/8083855/31771179-2fe919b6-b4ec-11e7-87fd-265250cb73ac.png)
try delete plasma cache and relogin on sddm:
`rm -rf ~/.cache/plasm* ~/.cache/ico*`

**Comment by varlesh** [comment]
Also on kde systemsettings set normal size for **border window** (it's not original translate):
![screenshot_20171019_164903](https://user-images.githubusercontent.com/8083855/31771555-9e185f90-b4ed-11e7-8b50-20b7bc810419.png)

**Comment by TamasBarta** [comment]
I tried all border sizes before and after deleting cache as well, but unfortunately with the same results. All the sizes below "Large" produce this result including Normal.

Is it possible that we have a different version of something? I have `0.10.5-1` of `kvantum-qt5`, see other versions mentioned above. I didn't mention, but I use Antergos with all updates installed. For example, your settings screen looks as if it's 5.10 or below. If that's the case, it may be possible that the theme needs some update to some change in KDE, but I'm not an expert in this 🙂

**Comment by varlesh** [comment]
> For example, your settings screen looks as if it's 5.10 or below

No, i'm set old version (because don't like new style)
I use KDE Neon User Edition:
- Plasma 5.11.1
- KDE Frwamework 5.39.0
- Qt 5.9.1
- Kvantum  0.10.5

Also on my nvidia aurorae earlier aurorae have wrong (blurred) rendering for buttons, i fix that. 
Try this, maybe it's help you - create hidden file on home directory  `.Xresources`:
```
Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb
```

**Comment by varlesh** [comment]
reboot pc and chaeck

**Comment by varlesh** [comment]
@TamasBarta It's reproduced on Adapta Nokto Kvantum theme? Or Arc / Arc Darker maybe?

**Comment by TamasBarta** [comment]
Wow, thank you very much! The `.Xresources` file made it work. Do you have any idea why I had wrong default values?

I tried with all the mentioned Kvantum themes, and the issue persisted with all of them.

**Comment by varlesh** [comment]
>  Do you have any idea why I had wrong default values?

I think it's plasma bug, but they don't want fix that. Sed more info here:
https://bugs.kde.org/show_bug.cgi?id=384457

**Comment by TamasBarta** [comment]
Okay, I see. Thanks! I'll check it out, and see what can I add to the issues there.
