### ISSUE TITLE
Adapta theme with plasma activity pager

### ISSUE THREAD

**Issue by alexjp** [PapirusDevelopmentTeam/adapta-kde#22]
Hi,

Thanks for the wonderfull theme !

I have an issue though, I use the plasma activity pager plasmoid, with activity names text.
With the adapta plasma theme, the colors of the active activity are the same as the colors of the text and also cannot see the icons of the windows in the activity.

Can this be fixed ?

Thanks !

**Comment by varlesh** [comment]
You can delete plasma/desktoptheme/Adapta/widgets/pager.svg. Reapply theme - will be used default pager from Breeze.

**Comment by alexjp** [comment]
Thanks.

But will you fix it later ? Yours is cool, maybe just make the "selected" overlay transparent ? ( dunno, I am not a graphic designer, sorry )

**Comment by varlesh** [comment]
Sorry, no.  Because transparent  - it's not Adapta style.

**Comment by alexjp** [comment]
:( damn .... ok, i understand. Thanks!

**Comment by alexjp** [comment]
BTW, an easy method: 

If you have the theme installed in the system, create : .local/share/plasma/desktoptheme/Adapta/widgets/pager.svgz in your home folder. Plasma will load that specific file just for pager ( and use the system theme, so no need to do this in every update ). 

Also instead of deleting, use the breeze pager, since it looks much better than none.

@varlesh should I close it or you do ?

**Comment by Tichy** [comment]
@alexjp alternatively, you could copy the original pager.svg to .local/share/plasma/desktoptheme/Adapta/widgets/pager.svg open it in an editor and substitute all occurrences of "opacity:1" with "opacity:0.8" (or the amount of shading that you want).

**Comment by alexjp** [comment]
BTW, can i close this ? maybe this info could go into readme or faq, but i guess the issue is closed, right ?

**Comment by varlesh** [comment]
yes. This not needed for readme, because it's optional issue
