### ISSUE TITLE
warning: adapta-kde: local (20171014-3) is newer than community (20171014-1)

### ISSUE THREAD

**Issue by JayTurnr** [PapirusDevelopmentTeam/adapta-kde#23]
As you're in [community](https://www.archlinux.org/packages/community/any/adapta-kde/) and [aur](https://aur.archlinux.org/packages/adapta-kde/), whenever I run an update on my computer I get this annoying message `warning: adapta-kde: local (20171014-3) is newer than community (20171014-1)` - please pick one or the other.

**Comment by varlesh** [comment]
I think adapta-kde package not needed on AUR, because now provide on Community Arch repo by @ArchangeGabriel

@now-im please remove adapta-kd from aur

**Comment by JayTurnr** [comment]
I bet you're well chuffed about that! :+1: By the way, I read your readme and spotted the -git version of the repo, I switched to using that so I won't be getting that annoying message anymore :P

**Comment by ArchangeGabriel** [comment]
The package in [community] was updated to `20171109` today, and I’ve removed the AUR package.

**Comment by now-im** [comment]
@varlesh @ArchangeGabbiel sorry I am very busy right now. Thanks for deleting it on my behalf.
