### ISSUE TITLE
Using GTK theme in Chrome doesn't work.

### ISSUE THREAD

**Issue by yaabdalla** [PapirusDevelopmentTeam/adapta-kde#24]
Using system title bar and borders, and GTK theme in Chrome doesn't work. It looks like this:

![screenshot_20171111_223913](https://user-images.githubusercontent.com/6026752/32696004-405aa2fe-c731-11e7-9a41-51fea8d1a5b2.png)

**Comment by varlesh** [comment]
I'm not developer Adapta GTK and not support yet. See readme, my pack for only Qt-apps!
Install [Adapta GTK Theme](https://github.com/adapta-project/adapta-gtk-theme) and apply on systemsettings for GTK apps

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/32696173-6333928c-c78a-11e7-8a9e-d045d75364f0.png)

**Comment by yaabdalla** [comment]
I am an idiot. Sorry. Thanks for your great work, and quick response.

**Comment by varlesh** [comment]
All fine, don't worry ))

**Comment by varlesh** [comment]
@yaabdalla Also i'm recommend use for KDE/Qt apps kvantum engine (install this too), see:
https://github.com/PapirusDevelopmentTeam/adapta-kde#recommendations

PS: for Kubuntu/KDE Neon kvantrm package available on papirus repo (for Arch-based distros on official repo). Set this engine on systemsetting as style

**Comment by varlesh** [comment]
**Screens for compare**
Breeze:
![screenshot_20171112_093351](https://user-images.githubusercontent.com/8083855/32696251-b3d14624-c78c-11e7-85f5-09995b840d44.png)
Kvantum:
![image](https://user-images.githubusercontent.com/8083855/32696253-be6c0a7e-c78c-11e7-9351-4c7a77f4d4c7.png)
