### ISSUE TITLE
Proposal for new wireless signal icon design

### ISSUE THREAD

**Issue by emilio-aburto** [PapirusDevelopmentTeam/adapta-kde#27]
Hello, I did a modification to the current wireless icons and it would be nice if you consider to integrate them into the repo. 
This is my proposal:
![proposal](https://user-images.githubusercontent.com/1557596/34012277-eeed6c0a-e0f1-11e7-81cd-1c703782a2e0.png)
And this is the current design, for comparison:
![current](https://user-images.githubusercontent.com/1557596/34012275-eecaaeae-e0f1-11e7-8a3f-907952a123a0.png)

If you approve I will do a PR with the changes. Thanks!

**Comment by varlesh** [comment]
Very good, i like it :)
Please not forgot use **ID name** for layers... PR welcome!

**Comment by emilio-aburto** [comment]
@varlesh I'm really newbie so I don't know if I did everything correctly but I'm currently using the modified theme and the wireless icons are shown as intended.
