### ISSUE TITLE
The progress bar on selected taskmanager buttons could use more contrast

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/adapta-kde#29]
![screenshot_20171225_164356](https://user-images.githubusercontent.com/2348771/34341217-01fb5934-e993-11e7-9704-c3becbbf70ff.png)

I think that, for example, making the cyan background more darker, would make the progress stand out better. I think that the issue here is that both color have similar brightness and saturation.

**Comment by varlesh** [comment]
It's Adapta colors, i don't want change it
