### ISSUE TITLE
Tray icon background not transparent

### ISSUE THREAD

**Issue by DevPre** [PapirusDevelopmentTeam/adapta-kde#31]
![screenshot_20171228_150826](https://user-images.githubusercontent.com/13499337/34413081-55774bf4-ebe1-11e7-92f6-aff90e4d1755.png)

Distro: Fedora KDE
I've only had this problem with Megasync, the official desktop client of Mega.co.nz.

**Comment by varlesh** [comment]
It's Arch problem or Qt5-version Mega. Qt4 worked fine. Anyway it's not Adapta bug:
![image](https://user-images.githubusercontent.com/8083855/34414176-2e5e2892-ec01-11e7-98ec-f5c6bf8f7047.png)

**Comment by varlesh** [comment]
Try with [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)

**Comment by varlesh** [comment]
https://github.com/meganz/MEGAsync/issues/157
