### ISSUE TITLE
Discover broken style

### ISSUE THREAD

**Issue by romanlex** [PapirusDevelopmentTeam/adapta-kde#32]
![image](https://user-images.githubusercontent.com/3369304/34447661-1f17ebec-ecf7-11e7-8b1e-02eba529b187.png)
Hello My discover with kvantum engine and adapta theme has broken style((

**Comment by SmartFinn** [comment]
Could you make a screenshot with an another Kvantum theme where it works correctly?

**Comment by romanlex** [comment]
@SmartFinn close please. Fix it when change color scheme in kde
