### ISSUE TITLE
Kvantum theme. Backspace arrow icon is stretched in text input fields.

### ISSUE THREAD

**Issue by cross1983** [PapirusDevelopmentTeam/adapta-kde#33]
Hi,
Thanks a lot for a very lovely theme.

Issue: Backspace arrow icon is stretched in text input fields for kvantum adapta theme.

![adaptanokto](https://user-images.githubusercontent.com/17809174/34655025-e48df578-f414-11e7-91ea-e03d203eb50e.png)

If I use Arc kvantum theme, there is no problem with backspace arrow icon

![screenshot_20180108_010941](https://user-images.githubusercontent.com/17809174/34655089-929ae0a4-f415-11e7-8948-0a8e33c74864.png)

**Comment by varlesh** [comment]
@cross1983 
Значки рисуются самим квантумом и в конфиге прописано:
```
small_icon_size=16
large_icon_size=32
button_icon_size=16
toolbar_icon_size=22
```
Что странно, у меня отображается нормальный значок:
![image](https://user-images.githubusercontent.com/8083855/34658577-83720af6-f449-11e7-8109-cfd6afaf32a6.png)
Куда копать хз

**Comment by varlesh** [comment]
Какая версия квантума и дистр?

**Comment by cross1983** [comment]
@varlesh 
Я нашёл причину - размер шрифта "Обычный текст". Я использую Noto Sans 11.
Если я уменьшу размер шрифта до 10, то значок отображается нормально. 

Видимо увеличенный размер шрифта расширяет размеры поля ввода и из-за этого масштабируется значок.

![image](https://user-images.githubusercontent.com/17809174/34662025-c6dfd56a-f45e-11e7-9ab4-0cc4ec102a09.png)

**Comment by cross1983** [comment]
@varlesh 
С темой KvAdaptaDark эффект такой же - значок растянутый.
Но вот с ArcDark всё хорошо, даже с 11 шрифтом.

**Comment by varlesh** [comment]
> Я нашёл причину - размер шрифта "Обычный текст". Я использую Noto Sans 11.

Думаю надо репортить этот баг разрабу квантума... т.к. KvAdaptaDark это апстрим.

> Но вот с ArcDark всё хорошо, даже с 11 шрифтом.

Поставил 11 шрифт - значок не растянулся.
Поставил 12 шрифт, а вот теперь да.
![image](https://user-images.githubusercontent.com/8083855/34663259-6c99977e-f46f-11e7-8022-097447db486d.png)
Я так понял значок использует площадь виджета Lineedit для установки размера.

**Comment by cross1983** [comment]
Как правильнее сделать? Тут issue закрываем, а в репе Kvantum открываем новое?

**Comment by varlesh** [comment]
Я уже написал... https://github.com/tsujan/Kvantum/issues/172
 пусть открыто пока тут

**Comment by cross1983** [comment]
спасибо за помощь :-)

**Comment by varlesh** [comment]
@cross1983 Проверь плиз с гита, вроде как поправил

**Comment by cross1983** [comment]
@varlesh 
Фикс помог, благодарю ;-)

![image](https://user-images.githubusercontent.com/17809174/34669821-a3bf4810-f484-11e7-8732-d675fd6f643b.png)

**Comment by cross1983** [comment]
Как я понял, разработчик kvantum попробует со своей стороны, что-нибудь сделать. Это issue можно закрывать?

**Comment by varlesh** [comment]
Пусть пока открыто... если разраб пофиксит, то я откачу коммит

**Comment by cross1983** [comment]
Кажется можно откатывать коммит. Сейчас для любителей больших шрифтов, значок масштабируется нормально.

**Comment by varlesh** [comment]
ок
