### ISSUE TITLE
"Pin" button missing to the Aurorae window decoration

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/adapta-kde#35]
I think that adding a pin button (window visible on all desktops) will be useful. At the moment, even if it's added to the titlebar (which is by default), it doesn't appear.

**Comment by varlesh** [comment]
Added:
![image](https://user-images.githubusercontent.com/8083855/34902578-f92bb1e2-f837-11e7-8a84-a694723bb10e.png)
