### ISSUE TITLE
Make circle-highlights an option

### ISSUE THREAD

**Issue by Scrumplex** [PapirusDevelopmentTeam/adapta-kde#40]
Related to #37.
I liked the circle-highlights, that have been replaced recently. I would love to have them as an option in Kvantum.

**Comment by varlesh** [comment]
Sorry, i'm not Kvantum developer and  i don't know how doing this as option...

PS: You can use previous commit build for temporary solution

**Comment by Scrumplex** [comment]
Can't you add a checkbox to the Kvantum settings for the theme?

**Comment by varlesh** [comment]
No, i'm not kvantum developer. Maybe @tsujan help you

**Comment by tsujan** [comment]
Please read this: https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/37#issuecomment-359202920

I added here that I won't make an exception for textless buttons because that's not how Qt works.

**Comment by Scrumplex** [comment]
@tsujan I didn't say, that there should be any difference. I just would like to have the option to use the circle highlighter (for any button/toolbar-icon) INSTEAD of the current one. 
I don't really care about that thing with the text, as I disable the text in every application.

**Comment by tsujan** [comment]
@Scrumplex 
That circle was an SVG element of this special Kvantum theme; it isn't a property of Kvantum itself.

> I don't really care about that thing with the text, as I disable the text in every application.

Some application can *enforce* the text, icon or the lack of them.

GTK and Qt are totally different toolkits with different "widgets". With Kvantum, GTK-like Qt themes became possible but, usually, they can't be *identical* to their GTK counterparts.

**Comment by tsujan** [comment]
And it's good to know that there are some Kvantum themes, to which no GTK theme could be similar, let alone identical ;)

**Comment by Scrumplex** [comment]
Does this mean, that you can't create a checkbox for this? If so, this issue can be closed.

**Comment by tsujan** [comment]
> Does this mean, that you can't create a checkbox for this?

No, I can't because, as explained above, the checkboxes are NOT for specific themes but for Kvantum properties.

**Comment by Scrumplex** [comment]
Okay then. Thanks for the quick replies.
