### ISSUE TITLE
[Enhancement] make close,maximize and minimize buttons bigger

### ISSUE THREAD

**Issue by pupyc** [PapirusDevelopmentTeam/adapta-kde#41]
make close,maximize and minimize buttons bigger to keep the consistency with gtk theme, to fill in titlebar completely

**Comment by pupyc** [comment]
See how they are different!

I think you can make plasma ones a little bit bigger and it will be perfect
GTK
![screenshot142](https://user-images.githubusercontent.com/31791780/37030613-9d777438-214c-11e8-907c-592e26e44231.png)

plasma
![](https://user-images.githubusercontent.com/8083855/33364323-5c0587b0-d4fd-11e7-950b-ff6907d5a10c.png)

**Comment by pupyc** [comment]
@varlesh @SmartFinn

**Comment by varlesh** [comment]
Big buttons - it's not save usable space on screen.

**Comment by varlesh** [comment]
Also on non-Gnome DE's (XFCE, LXDE) used small buttons too. I 'don't like big buttons

**Comment by pupyc** [comment]
@varlesh 
> Also on non-Gnome DE's (XFCE, LXDE) used small buttons too. I 'don't like big buttonsI

I don't mean big buttons like gnome ones, I asked for a xfce/mate-like button the screenshot above is not gnome but it is mate!

Gnome
![titlebar](https://user-images.githubusercontent.com/31791780/37145910-4212879e-22d3-11e8-8fe5-7e8fd4515637.png)

Mate/xfce
![titlebar-1](https://user-images.githubusercontent.com/31791780/37145972-7ca5cd1c-22d3-11e8-838d-3c5a7379eaef.png)

Plasma
![titlebar-2](https://user-images.githubusercontent.com/31791780/37146240-3b3d33b4-22d4-11e8-829e-a9b49bc7776f.png)

**Comment by pupyc** [comment]
see how plasma button are smaller than xfce/mate one, and there is a space to make them bigger without making the titlebar bigger

**Comment by pupyc** [comment]
maybe something like this 
![33364323-5c0587b0-d4fd-11e7-950b-ff6907d5a10c](https://user-images.githubusercontent.com/31791780/37146563-2bc48670-22d5-11e8-88d5-cc039d004e36.png)

**Comment by varlesh** [comment]
@pupyc Big buttons good looking for CSD only. For other DE's it's not practical and not save usable space on screen.
I don't want change it... You can fork aurorae theme and change it for your self

**Comment by pupyc** [comment]
there is a lot of space wasted, that can be used, specially when you use touchpads


![titlebar-2](https://user-images.githubusercontent.com/31791780/37160859-42c85126-2302-11e8-8638-f008427dca5d.png)

**Comment by pupyc** [comment]
@varlesh see how there is space to make them clear, now it is very hard to click them

![close](https://user-images.githubusercontent.com/31791780/37182804-08718aaa-2344-11e8-98dc-f54ba464e380.png)

![screenshot](https://user-images.githubusercontent.com/31791780/37182853-5c2e4f52-2344-11e8-9342-e4548092806e.png)

see result if you like it ?

**Comment by pupyc** [comment]
see breeze and adapta icons

![adapta vs breeze](https://user-images.githubusercontent.com/31791780/37183443-22b6d43a-2347-11e8-8075-bd82f8606f2a.png)

**Comment by varlesh** [comment]
@pupyc No, see hover and pressed buttons. Use 3px space only (without down shadow):
![image](https://user-images.githubusercontent.com/8083855/37190711-cfe9e480-2374-11e8-9ac1-586664f5704d.png)
Breeze - it's QML-based decoration and doesn't matter with Aurorae
