### ISSUE TITLE
Gap between panel and popups

### ISSUE THREAD

**Issue by Scrumplex** [PapirusDevelopmentTeam/adapta-kde#45]
If a panel is at the top of the screen, it's popup-panels have a gap.
![Screenshot](https://x.scrumplex.rocks/img/1522182080.png)

**Comment by varlesh** [comment]
not confirm this, try remove plasma cache and relogin on system:
```
rm -rf ~/.cache/plasm*
```
![image](https://user-images.githubusercontent.com/8083855/37995439-89c6319c-3225-11e8-90da-62f1c7b41b07.png)

**Comment by Scrumplex** [comment]
That just fixed it
