### ISSUE TITLE
Device Notifier icon is missing after the last update

### ISSUE THREAD

**Issue by yn4v4s** [PapirusDevelopmentTeam/adapta-kde#46]
```
potter@ripjaws:~$ dpkg -l adapta-kde
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-==================================================
ii  adapta-kde             20180331-126+pkg all              Adapta KDE
```
![screenshot_20180402_141528](https://user-images.githubusercontent.com/35275827/38208953-a68fdb66-3680-11e8-8fdf-0db7c8482138.png)
![screenshot_20180402_141625](https://user-images.githubusercontent.com/35275827/38208962-b3ad7786-3680-11e8-8377-a7824cf5cac1.png)

**Comment by yn4v4s** [comment]
Sorry, I solved it by deleting my .cache directory entirely, because deleting icon-cache.kcache wasn't enough.

**Comment by varlesh** [comment]
it's old plasma bug. When theme upadted, used old cache
