### ISSUE TITLE
Add new network icons

### ISSUE THREAD

**Issue by pupyc** [PapirusDevelopmentTeam/adapta-kde#47]
There are some new icons in the desktop theme for network

https://phabricator.kde.org/D11390

![Spectacle.W12059](https://phabricator.kde.org/file/data/qx4cywzqcql5mmo6dvfh/PHID-FILE-mpabmzjpz3pdc5oyowtk/Spectacle.W12059.png)

**Comment by yn4v4s** [comment]
Nice

**Comment by varlesh** [comment]
It's already on upstream?

**Comment by varlesh** [comment]
@yn4v4s this icons now different:
![image](https://user-images.githubusercontent.com/8083855/38212545-2b1fddba-36cf-11e8-9504-7f6efab202f7.png)

**Comment by varlesh** [comment]
@yn4v4s try remove cache.
See on svg used this ID's:
![image](https://user-images.githubusercontent.com/8083855/38214162-d4891614-36d4-11e8-93a7-3d210a07f14e.png)
![image](https://user-images.githubusercontent.com/8083855/38214175-e08d8ac6-36d4-11e8-93e5-7545102369d1.png)

**Comment by yn4v4s** [comment]
@varlesh I removed cache a couple hours ago, due to Device Notifier icon issue... and wireless icons have not changed.

**Comment by varlesh** [comment]
on your screen icon `network-wireless-20` or `network-wireless-connected-20`
> I removed cache a couple hours ago

i committed this an hour ago

**Comment by varlesh** [comment]
You can check this, open file:
/usr/share/plasma/desktoptheme/Adapta/icons/network.svg

**Comment by yn4v4s** [comment]
look
![screenshot_20180402_163815](https://user-images.githubusercontent.com/35275827/38214997-4c1a24b6-3694-11e8-96b5-500cfd0829c7.png)

**Comment by yn4v4s** [comment]
> on your screen icon network-wireless-20 or network-wireless-connected-20

I can't find those files...

**Comment by yn4v4s** [comment]
Are the ppa packages up tu date?

**Comment by varlesh** [comment]
ppa update each 24 hours

**Comment by varlesh** [comment]
you can update from git:
`wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/adapta-kde/master/install.sh | sh`

**Comment by yn4v4s** [comment]
this is what I have now:
`adapta-kde             20180331-126+pkg`

**Comment by pupyc** [comment]
@varlesh I think the `off` icon is not representative of what is happening, a better choice will be https://material.io/icons/#ic_signal_wifi_off

**Comment by yn4v4s** [comment]
@pupyc, I agree

**Comment by pupyc** [comment]
@varlesh also `network-wireless-limited` will have a better look if it was bigger, see this
https://material.io/icons/#ic_perm_scan_wifi

**Comment by varlesh** [comment]
you really like this?
![image](https://user-images.githubusercontent.com/8083855/38216210-2f94787c-36db-11e8-83e1-4d6c33f92ade.png)

**Comment by pupyc** [comment]
> you really like this?

Thats better imo

**Comment by varlesh** [comment]
maybe better use papirus style?
![image](https://user-images.githubusercontent.com/8083855/38216356-9aedf9e0-36db-11e8-9822-83f9f25f4c6f.png)

**Comment by varlesh** [comment]
30% opacity interface icon and 100% cross

**Comment by pupyc** [comment]
> maybe better use papirus style?

Thats even better!

**Comment by pupyc** [comment]
@varlesh also the the `network-wireless-available` would be better with a question mark, like android imo

![](https://forums.androidcentral.com/attachments/android-5-0-lollipop/153462d1418217559t-annoying-wi-fi-networks-available-notification-1418217555933.jpg)

**Comment by varlesh** [comment]
updated

**Comment by pupyc** [comment]
what about 

> @varlesh also network-wireless-limited will have a better look if the exclamation mark was bigger, see this
https://material.io/icons/#ic_perm_scan_wifi

**Comment by pupyc** [comment]
> updated

nice, but I noticed you've changed the `network-wireless-disconnected` and `network-wireless-off` icons, is that intentionally or a mistake from your part ?

**Comment by pupyc** [comment]
also I think the `x` symbol in `network-wireless-off` is a little bit small, comparing it with the question mark in `network-wireless-available`

**Comment by pupyc** [comment]
@varlesh 

> what about
>
> > @varlesh also network-wireless-limited will have a better look if the exclamation mark was bigger, see this
> https://material.io/icons/#ic_perm_scan_wifi

**Comment by yn4v4s** [comment]
I just updated to `adapta-kde             20180402-133`, but I do not see change on the icons; is this package up to date???

**Comment by varlesh** [comment]
@yn4v4s remove cache

@pupyc 
> also network-wireless-limited will have a better look if the exclamation mark was bigger, see this
https://material.io/icons/#ic_perm_scan_wifi

Nope. Because used single style for all icons:
![image](https://user-images.githubusercontent.com/8083855/38302580-3b7f1af4-3814-11e8-968c-d1c9495461cc.png)

**Comment by yn4v4s** [comment]
@varlesh, yes I see the change now;
there is another update `adapta-kde_20180403-137`, what's new???

**Comment by pupyc** [comment]
@varlesh 

> also I think the x symbol in network-wireless-off is a little bit small, comparing it with others, see the question mark in network-wireless-available ...

**Comment by varlesh** [comment]
@pupyc "x" little increased. 
Also now `limit` and `off` have highlight color.
Single size used for `limit` and `available` only. Because "x" less "!" or "?"
![image](https://user-images.githubusercontent.com/8083855/38319615-47162cac-3843-11e8-9999-ea02815a3f6d.png)

**Comment by varlesh** [comment]
@yn4v4s 
This ppa builded automaticaly with launchpad farm every 24 hours (if available new commits)
> what's new???

See commits

**Comment by pupyc** [comment]
@varlesh hmm. nice! what about changing `available` and `locked` color, to go with other icons

if you change the color you can make the icons `available, locked, limit ...` bigger because there will be no color overlap (contrast issues), also you can make all them the same size,

**Comment by pupyc** [comment]
![locked](https://user-images.githubusercontent.com/31791780/38320612-96c084c4-3824-11e8-8e36-df6b19578012.png)

see how this icon will not have good contrast in big screen because they will be smaller and smaller in bigger screens
