### ISSUE TITLE
Adjust panel shadows

### ISSUE THREAD

**Issue by DiegoVicen** [PapirusDevelopmentTeam/adapta-kde#54]
In KDE, panel shadows are overlapped on top of windows, even if they are active. This produces some strange effects and on certain applications which use a lot of vertical screen real state, it can affect the experience sometimes.

![screenshot_20180501_231129](https://user-images.githubusercontent.com/7013448/39494254-f89e0956-4d95-11e8-8bdf-27df35c57a53.png)

However, I understand that this panel shadows are a key part of the theme aesthetic: removing them results in an uncanny flatness, and it is not annoying if the pannel is placed on the upper edge of the screen as shown in the screenshots. For that reason, I have adjusted the shadows to be reduced only in upper part of the panel, being more subtle but still present.

![screenshot_20180501_230239](https://user-images.githubusercontent.com/7013448/39494333-4c76e2fa-4d96-11e8-946b-f28ea3077664.png)

I don't know if this aligns with the maintaners target, but it can be positive for some users if they use lower panels. If there is interest in it, I can make a pull request for this resource to be merged upstream. Last but not least, thank you all for your hard work making such a great theme!

**Comment by varlesh** [comment]
Thx for your contribution. But i don't want change shadows. I think it's not critical and text readable
