### ISSUE TITLE
Space between lines in context menus

### ISSUE THREAD

**Issue by hondacivika** [PapirusDevelopmentTeam/adapta-kde#56]
Is there a way to reduce the spaces between lines in context menus in the desktop and Dolphin and other KDE applications? Because using the Adapta theme there is too much space wasted unlike the default Breeze theme were the menus are very tight.

I tried changes some of the settings in the Kvantum but I couldn't figure out how to do it.

![image](https://user-images.githubusercontent.com/38983194/39635842-46af6fda-4fc7-11e8-8163-b4228a63726f.png)
![image](https://user-images.githubusercontent.com/38983194/39635847-4a1b6dfe-4fc7-11e8-946b-3eff1590f65d.png)

**Comment by varlesh** [comment]
```
[MenuItem]
inherits=PanelButtonCommand
frame=true
frame.element=menuitem
interior.element=menuitem
indicator.element=menuitem
text.normal.color=#d3dae3
text.focus.color=white
text.margin.top=1
text.margin.bottom=1
text.margin.left=4
text.margin.right=4
frame.top=0
frame.bottom=0
frame.left=0
frame.right=0
text.bold=false
min_width=0
min_height=0
frame.expansion=0
```
