### ISSUE TITLE
Media indicator icon changed after upgrading Plasma to 5.13

### ISSUE THREAD

**Issue by marhkb** [PapirusDevelopmentTeam/adapta-kde#58]
This looks now like the icon from Breeze.
Cache ".cache/plasma*" was deleted but to no avail.
![adapta_media](https://user-images.githubusercontent.com/3630213/41427729-20eec78a-7008-11e8-9e29-a4ed93c01101.png)

**Comment by varlesh** [comment]
I don't know, for me used icons from plasma theme (with PlayBar2):
![image](https://user-images.githubusercontent.com/8083855/41428453-36b42eee-701b-11e8-910a-2fd466096653.png)

**Comment by marhkb** [comment]
Yes can confirm. Playbar2 works.

**Comment by varlesh** [comment]
@marhkb i'm fix this soon for MediaController

**Comment by varlesh** [comment]
fixed
