### ISSUE TITLE
dolphin and hidden menubar "icon"

### ISSUE THREAD

**Issue by ahjolinna** [PapirusDevelopmentTeam/adapta-kde#6]
on dolphin I have the menu bar hidden, plus the toolbar position is on the left instead of on the more typical "top", so with this adapta theme the "menu bar" icon the toolbar becomes too wide (and looks weird). I have never used kvantum before this so I don't know where/how to fix this myself.

(menu bar hidden)
![image](https://user-images.githubusercontent.com/6993072/30544050-e4cd7808-9c8d-11e7-8331-a053f3533beb.png)

(menu bar unhidden)
![image](https://user-images.githubusercontent.com/6993072/30544099-0950646a-9c8e-11e7-8651-9c147e01640b.png)

**Comment by varlesh** [comment]
menubar used with shadow and toolbar too, because some apps not have toolbar, for example clementine.
I recommend use this theme with aurorae decoration and up position for toolbar and menubar.

**Comment by ahjolinna** [comment]
the problem is the stupid "arrow" on the right of the (menubar) icon, which widens the toolbar too much if you have it on the left (or right) position instead, this oc doesn't exist on breeze : 

![image](https://user-images.githubusercontent.com/6993072/30556446-8be3ab7e-9cb3-11e7-83c7-7bb4221fd955.png)

**Comment by varlesh** [comment]
You can delete `indicator.element=tarrow` from section  `[ToolbarButton]` on Adapta.kvconfig

**Comment by varlesh** [comment]
@ahjolinna i'm disable arrow on PanelButtonTool

**Comment by ahjolinna** [comment]
@varlesh : thank you, that worked

**Comment by ahjolinna** [comment]
okay, the toolbar is still (overall) on the more "spacious" side compare to breeze, but now its at least better and doesn't look weird

**Comment by varlesh** [comment]
Buttons have gradient shadows

**Comment by ahjolinna** [comment]
I'm really not sure if the shadows are responsible for it, doesn't really matter. ..it's More or less fine as it is
