### ISSUE TITLE
Volume icons are now a purple tinge.

### ISSUE THREAD

**Issue by cj-sv** [PapirusDevelopmentTeam/adapta-kde#64]
* Package: adapta-kde
* Version: 20180618-155+pkg1~ubuntu18.04.1
* APT-Sources: http://ppa.launchpad.net/papirus/papirus/ubuntu bionic/main amd64 Packages
* Plasma:  5.12.5

Not sure if intentional, but it doesn't fit well with the theme.  
  
![screenshot_20180618_194502](https://user-images.githubusercontent.com/11567756/41534397-0a481726-7331-11e8-9f26-5a37a4072715.jpeg)

**Comment by varlesh** [comment]
now all 32px and high icons have material style and colorized. 
22px icons as usual monochrome:
![image](https://user-images.githubusercontent.com/8083855/41534668-5d9bfd3c-7310-11e8-967c-a1e8333f756b.png)
![image](https://user-images.githubusercontent.com/8083855/41534682-6b0b9310-7310-11e8-967b-a1afbd0e12fd.png)
![image](https://user-images.githubusercontent.com/8083855/41534709-82e820b6-7310-11e8-8887-c0e61552a9cb.png)
![image](https://user-images.githubusercontent.com/8083855/41534730-916cf3d2-7310-11e8-8deb-f9515a798134.png)
PS: It's materia KDE screens, but icons similar with Adapta

**Comment by cj-sv** [comment]
Ohh, I see. I didn't notice the other icons getting colored. Thank you for pointing that out.

**Comment by varlesh** [comment]
Yes-yes... all icons :)
and media too:
![image](https://user-images.githubusercontent.com/8083855/41535042-e9b5b1ea-7311-11e8-9589-7532af18b254.png)

**Comment by flipwise** [comment]
I would agree though that the purple color for the volume OSD looks out of place. Maybe the default Adapta viridian color would look better if wanting it colorized?
