### ISSUE TITLE
Kwin wayland crashes 

### ISSUE THREAD

**Issue by now-im** [PapirusDevelopmentTeam/adapta-kde#65]
Because of Adapta Kwin wayland crashes when I try to close an application or switch to other apps using alt+tab.
I filed a bug in KDE but others have also confirmed it is a theme problem.
https://bugs.kde.org/show_bug.cgi?id=395346

**Comment by varlesh** [comment]
It's aurorae engine bug, not my theme. On Xorg all worked fine

**Comment by now-im** [comment]
Yes, in xorg no problem. Crashes happen in wayland only.

**Comment by now-im** [comment]
Seems like unrelated to papirus.
