### ISSUE TITLE
Odd black border thing on popup menus?

### ISSUE THREAD

**Issue by BobbyWibowo** [PapirusDevelopmentTeam/adapta-kde#68]
What the title says. Here's an example:
![Screenshot](https://i.fiery.me/jOrC.png)
Notice the few pixels thick of black border?

I'm guessing it's supposed to show shadow, but something broke down. I can't really guess what it is though.
I have been using this for a few weeks and it has always been working just fine, but then today all of a sudden it behave like this.
I'm on KDE neon 5.13.2 btw.

**Comment by BobbyWibowo** [comment]
Turns out this happens on all Kvantum themes that uses shadow thingy.
I still couldn't figure out the cause tho. Like, other things that uses shadow without Kvantum (e.i. window shadow, or Breeze widget style) work just fine.

**Comment by varlesh** [comment]
Previous i'm use intel HD4000 and all themes worked fine with good rendering. Now i'm use nvidia and all rendering fine too. Try ask about this problem on kvantum developer @tsujan
Also try change engine on KDE systemsettings to OpenGL, Xrender and etc. Maybe need disable some effect on Plasma, for example Blur or Translucency

**Comment by varlesh** [comment]
@BobbyWibowo  on your screenshot - it's plasma. Kvantum draw only windows and dialogs.

**Comment by tsujan** [comment]
I was called with an email notification from this page.

As @varlesh correctly said, this is about Plasma, not Kvantum. The first screenshot may show the lack of compositing with Plasma menus.

**Comment by BobbyWibowo** [comment]
Yeah, it seems to be a problem with my graphics or something. Plasma's blur and transparency effects indeed completely do not work for whatever reasons. Tried going through X logs but there was nothing suspicious. Tried reinstalling all mesa drivers, nothing. The only time it could work was when I completely disabled hardware acceleration, but it's pretty much unusable due to the sluggishness. Sigh.

**Comment by BobbyWibowo** [comment]
This has been solved. It indeed had something to do with X server.
The whole thread as well as the way I solved it, for those who may need it: https://www.reddit.com/r/kde/comments/8x2k54/kde_neon_desktop_composition_not_working/.
