### ISSUE TITLE
[color-scheme & kvantum & yakuake & konsole]New colors for text/icons on white backgrond

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/adapta-kde#7]
Now used:
```
text.normal.color=#7f898e
text.focus.color=#575d61
text.press.color=#575d61
text.toggle.color=white
```

popup menu on gnomeshell panel #5c6569
Settings sidebar (Ubuntu 17.10) #5a6368
Nautilus sidebar #81898c

**Comment by YangMame** [comment]
will you add a dark theme ?
I want to use a dark theme to protect my eyes...
thanks !

**Comment by varlesh** [comment]
@YangMame maybe...

**Comment by YangMame** [comment]
and I'm using gentoo with your script

**Comment by YangMame** [comment]
okay looking forward to your updates

**Comment by varlesh** [comment]
`Adapta-Nokto` it's dark theme... also we need add version for Papirus icons too.
@SmartFinn What you think about that?

**Comment by SmartFinn** [comment]
@varlesh sure, why not.

**Comment by vltr** [comment]
:+1: for the dark theme. I actually use GS, but to be able to use Adapta also in Qt/KDE applications would be awesome (for uniform looks) :wink:

**Comment by varlesh** [comment]
AdaptaNokto added

**Comment by varlesh** [comment]
@YangMame @vltr all done!
![image](https://user-images.githubusercontent.com/8083855/30606251-1eb84fc6-9d82-11e7-9985-8beecdcd7d0c.png)

**Comment by vltr** [comment]
@varlesh nice! I already applied here too - as I mentioned earlier, I use GS - and my Qt based apps (using kvantum and qt5ct) now looks even more like GTK ones than with my clumsy qt5ct .qss file to match some basic stuff! :wink: 

![screenshot_20170919-024018](https://user-images.githubusercontent.com/1540275/30606644-ba44f8e8-9d48-11e7-85f7-fb2864c4fd9b.png)

**Comment by YangMame** [comment]
@varlesh thanks ! I love it

**Comment by iamtodor** [comment]
@varlesh could you please share the name of app, that shows GPU/CPU/HDD/SSD temperature?

**Comment by varlesh** [comment]
https://store.kde.org/p/998915/
