### ISSUE TITLE
Icon request: systemtray icon for krfb

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/adapta-kde#73]
![image](https://user-images.githubusercontent.com/11857205/43785776-41013702-9a91-11e8-887b-808b3c90757b.png)

It looks different than the others.

**Comment by varlesh** [comment]
icon not applied from plasma theme

**Comment by varlesh** [comment]
icon added, but this senselessly now

**Comment by trmdi** [comment]
I've seen the new icon.

**Comment by trmdi** [comment]
Excuse me, it seems that the Discord icon on the system tray does not come from your icon theme?

![image](https://user-images.githubusercontent.com/11857205/46123807-9fd98000-c24a-11e8-8d43-1cef2648f7e8.png)

**Comment by SmartFinn** [comment]
@trmdi see [Hardcoded tray icons](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#hardcoded-tray-icons)
