### ISSUE TITLE
Progress spinner animation should be more subtle

### ISSUE THREAD

**Issue by benburrill** [PapirusDevelopmentTeam/adapta-kde#76]
When launching applications from the task manager and also in some other contexts a progress spinner appears around icons.  The default in KDE (or at least in the Breeze theme) is a simple circle outline spinner, but the adapta-kde desktop theme changes this to big orbiting orange circles.  This isn't so bad in task manager (although I still prefer the KDE default).  However, it becomes really ugly (IMO) on the system tray, particularly when connecting to a wifi network.  The orange circles just seem really out of place and are far too big.

**Comment by varlesh** [comment]
`sudo rm /usr/share/plasma/desktoptheme/Adapta/widgets/busywidget.svg`
