### ISSUE TITLE
Option to remove titlebar?

### ISSUE THREAD

**Issue by PapyElGringo** [PapirusDevelopmentTeam/adapta-kde#77]
Hello,

I love the Adapta theme and I would love to use it but currently im forced to keep breeze at window decoration because it's the only one who provide me the option to remove the title bars.

Im used to work with shortcuts or meta-windows behavior to manipulate my windows.

I also use the gtk3-nocsd scripts to bring back my shadow backdrop on gtk apps and got double titlebar in thoses cases.

That's why I would love to be able to remove the title bar of adapta to style get the border and the window style.

Is there a way to achieve this today?

Thanks

**Comment by varlesh** [comment]
On KDE used option:
ALT+F3 > additional > No Borders (It's not original translate)
But buttons will be disappear

**Comment by PapyElGringo** [comment]
I know this option but the difficulty for me is that I want to keep the borders and the shadows just remove the title bar.

And of course remove the buttons also.

For example let me show you how I do this with breeze:

![remove title bar option](https://user-images.githubusercontent.com/3754825/45359287-5a6f4e80-b5cc-11e8-8cff-1141e8420b83.png)

**Comment by varlesh** [comment]
@PapyElGringo It's doing easy. Open file `Adaptarc` on aurorae theme and set 0 to:
```
ButtonHeight=0
ButtonWidth=0
TitleHeight=0
```
![image](https://user-images.githubusercontent.com/8083855/45402791-9821b500-b668-11e8-8852-e9647ebe4b67.png)

**Comment by varlesh** [comment]
@PapyElGringo Maybe you know tool for move window buttons on toolbar?
For example:
![screenshot_20180912_085801](https://user-images.githubusercontent.com/8083855/45403317-c902e980-b66a-11e8-9dfa-07964f5579df.png)

**Comment by varlesh** [comment]
With Active Window Control buttons show on panel.... but how use that on toolbar?
![image](https://user-images.githubusercontent.com/8083855/45403959-0c128c00-b66e-11e8-9937-deaf2a7ab912.png)

**Comment by varlesh** [comment]
readme updated

**Comment by PapyElGringo** [comment]
Thanks dude I had to play a bit with the title borders to get the same space used at the top and the left/rights border but yeaah I did it!

Have a nice day

**Comment by varlesh** [comment]
@PapyElGringo Also you can reduce `TitleEdgeTop` for example to `TitleEdgeTop=-4`... but some dialogs can not be focused for move window, need set  hotkey for that on kwin
before:
![image](https://user-images.githubusercontent.com/8083855/45412917-f78fbd00-b688-11e8-87bc-418bb8b49293.png)
after:
![image](https://user-images.githubusercontent.com/8083855/45413009-273ec500-b689-11e8-896b-ac395d7120e3.png)
