### ISSUE TITLE
Background tabs are too dark using new version of chrome

### ISSUE THREAD

**Issue by JairoAlonso25** [PapirusDevelopmentTeam/adapta-kde#78]
Using new Chrome Version 69.0.3497.92 (Official Build) (64-bit) makes background tabs too dark:

![image](https://user-images.githubusercontent.com/2227972/45582041-b9ec8900-b86e-11e8-923e-dfb38d864b7f.png)

I tested it with Adapta and Adapta-Nokto

**Comment by varlesh** [comment]
This repo for only KDE/Qt. Chrome and Cromium it's GTK apps!!!
Use old version:

- open `chrome://flags/#top-chrome-md`
- and set `normal`
