### ISSUE TITLE
Follow upstream changes

### ISSUE THREAD

**Issue by dooqob** [PapirusDevelopmentTeam/adapta-kde#79]
Hello! there is alot of changing is happening to [Adapta-GTK-Theme](https://github.com/adapta-project/adapta-gtk-theme) Thanks in advance.

**Comment by varlesh** [comment]
omg again....

**Comment by varlesh** [comment]
Theme global updated:
![image](https://user-images.githubusercontent.com/8083855/46253577-08656e80-c490-11e8-86a4-eb225beff80d.png)
All elements changed, we must change more themes and fix that.... BUT i don't want doing this and i don't like new style and colors..
I think current theme likely will be archived or dropped

**Comment by jupitteer** [comment]
So is anything being done right now to develop this?

**Comment by SmartFinn** [comment]
The development of the project is stopped until someone forks adapta-gtk-theme v3.94.0.149. If this not happens, adapta-kde will be closed.

**Comment by Jacalz** [comment]
I really hope that this can keep on using the old design, I have forked the old version of Adapta but I don't have the skills nor time to maintaining it. At least there is a repo for it now: https://github.com/Jacalz/adapta-gtk-theme-legacy

**Comment by quantumkv** [comment]
Launchpad still contains the non-updating .deb file of the previous version for download. Can confirm that the deb works perfectly.

For Ubuntu 18.10:
https://launchpad.net/~tista/+archive/ubuntu/adapta/+files/adapta-gtk-theme_3.94.0.149-0ubuntu1~cosmic1_all.deb

For Ubuntu 18.04:
https://launchpad.net/~tista/+archive/ubuntu/adapta/+files/adapta-gtk-theme_3.94.0.149-0ubuntu1~bionic1_all.deb

@varlesh Maybe you should add these links to the readme.

**Comment by trmdi** [comment]
Is this the time for your start-from-scratch Plasma theme? @varlesh

**Comment by jupitteer** [comment]
Well this sucks. So we're gonna have no option for adapta on kde if we want to use the new version?

**Comment by SmartFinn** [comment]
@jupitteer perhaps someone will create a port the new Adapta theme for KDE, but not in this project. It requires a lot of time for a theme that we don't really like it.

**Comment by varlesh** [comment]
Guys, new Adapta change all elements and i don't like new style and colors. We lost soft colors, shadows from toolbar, hilight color and more etc... you can install new version and compare with old Adapta.
Better solution for now - use Adapta 3.94 or Materia KDE

**Comment by varlesh** [comment]
For compare:
old Adapta (Dolphin & Nautilus):
![image](https://user-images.githubusercontent.com/8083855/46307885-3ef2d480-c5c9-11e8-9a92-ad4cde2b55f4.png)
new Adapta (Dolphin & Nautilus):
![image](https://user-images.githubusercontent.com/8083855/46307976-78c3db00-c5c9-11e8-9beb-e62656cab662.png)

**Comment by jupitteer** [comment]
So is this continuing if tista9000 adds the old theme as an official option in the theme, like adapta-nokto and adapta-brila?

**Comment by SmartFinn** [comment]
@jupitteer Oh sure. It also can be another developer who will continues maintenance the old theme.

**Comment by varlesh** [comment]
@jupitteer If old theme will be restored or forked and supported on future - yes, of course.
But i don't understand why tista not create new theme with new name and new colors and elements?
I'm not seen old style on new Adapta theme - it's very different themes

**Comment by ghuwe** [comment]
There's a notice in https://github.com/adapta-project/adapta-gtk-theme that says:

>Reverted all changes to 3.94.0.x and I will move to somewhere else.

which is great news.

**Comment by varlesh** [comment]
@jupitteer old theme restored https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.95.0.7. Everything remains as before
